### PR TITLE
updated lab plot colours to match others

### PR DESCRIPTION
**Pull request by ktchufong**
APOLOGIEs many merge conflicts .....

i only:
changed the code chunk for lab_dist.png in tha notebook
updated lab_dist.png
reknitted Report.pdf to reflect changes

### CODE REVIEW

**Comment by dvnguyen02** [comment]
I think the conflict happened since you were working on the yesterday repo?

**Review by dvnguyen02 — COMMENTED** [review]
it seems like you have not cloned the repo before you push your code in

**Comment by dvnguyen02** [comment]
would there be any chance that you could save your code on the notebook file some where then clone the repo Then edit the code in the repo and push them back?

**Review by dvnguyen02 — APPROVED** [review]
looks very good

**Comment by ktchufong** [comment]
i made new branch, hopefully correct merge

**Pull request closed without merging**
